export const products = [
  {
    id: 1,
    name: "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops",
    price: 109.95,
    category: "men's clothing",
    image: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
    stock: 120,
    isSelected: false,
    color: "Blue",
    size: "Medium",
    quantity: 1,
  },
  {
    id: 2,
    name: "Mens Casual Premium Slim Fit T-Shirts",
    price: 22.3,
    category: "men's clothing",
    image:
      "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
    stock: 259,
    isSelected: false,
    color: "Gray",
    size: "Large",
    quantity: 1,
  },
  {
    id: 3,
    name: "Mens Cotton Jacket",
    price: 55.99,
    category: "men's clothing",
    image: "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
    stock: 500,
    isSelected: false,
    color: "Green",
    size: "Large",
    quantity: 1,
  },
  {
    id: 4,
    name: "Mens Casual Slim Fit",
    price: 15.99,
    category: "men's clothing",
    image: "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
    stock: 430,
    isSelected: false,
    color: "Black",
    size: "Small",
    quantity: 1,
  },
  {
    id: 5,
    name: "John Hardy Women's Legends Naga Gold & Silver Dragon Station Chain Bracelet",
    price: 695,
    category: "jewelery",
    image: "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
    stock: 400,
    isSelected: false,
    color: "Silver",
    size: "One Size",
    quantity: 1,
  },
  {
    id: 6,
    name: "Solid Gold Petite Micropave",
    price: 168,
    category: "jewelery",
    image: "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg",
    stock: 70,
    isSelected: false,
    color: "Gold",
    size: "One Size",
    quantity: 1,
  },
  {
    id: 7,
    name: "White Gold Plated Princess",
    price: 9.99,
    category: "jewelery",
    image: "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
    stock: 400,
    isSelected: false,
    color: "White Gold",
    size: "One Size",
    quantity: 1,
  },
  {
    id: 8,
    name: "Pierced Owl Rose Gold Plated Stainless Steel Double",
    price: 10.99,
    category: "jewelery",
    image: "https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg",
    stock: 100,
    isSelected: false,
    color: "Rose Gold",
    size: "One Size",
    quantity: 1,
  },
  {
    id: 9,
    name: "WD 2TB Elements Portable External Hard Drive - USB 3.0",
    price: 64,
    category: "electronics",
    image: "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg",
    stock: 203,
    isSelected: false,
    color: "Black",
    size: "2TB",
    quantity: 1,
  },
  {
    id: 10,
    name: "SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s",
    price: 109,
    category: "electronics",
    image: "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg",
    stock: 470,
    isSelected: false,
    color: "Black",
    size: "1TB",
    quantity: 1,
  },
  {
    id: 11,
    name: "Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5",
    price: 109,
    category: "electronics",
    image: "https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg",
    stock: 319,
    isSelected: false,
    color: "Silver",
    size: "256GB",
    quantity: 1,
  },
  {
    id: 12,
    name: "WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive",
    price: 114,
    category: "electronics",
    image: "https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg",
    stock: 400,
    isSelected: false,
    color: "Black",
    size: "4TB",
    quantity: 1,
  },
  {
    id: 13,
    name: "Acer SB220Q bi 21.5 inches Full HD (1920 x 1080) IPS Ultra-Thin",
    price: 599,
    category: "electronics",
    image: "https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg",
    stock: 10,
    isSelected: false,
    color: "Black",
    size: "21.5 inches",
    quantity: 1,
  },
  {
    id: 14,
    name: "Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor",
    price: 999.99,
    category: "electronics",
    image: "https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg",
    stock: 140,
    isSelected: false,
    color: "Black",
    size: "49 inches",
    quantity: 1,
  },
  {
    id: 15,
    name: "BIYLACLESEN Women's 3-in-1 Snowboard Jacket Winter Coats",
    price: 56.99,
    category: "women's clothing",
    image: "https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg",
    stock: 235,
    isSelected: false,
    color: "Red",
    size: "Large",
    quantity: 1,
  },
  {
    id: 16,
    name: "Lock and Love Women's Removable Hooded Faux Leather Moto Biker Jacket",
    price: 29.95,
    category: "women's clothing",
    image: "https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_.jpg",
    stock: 340,
    isSelected: false,
    color: "Brown",
    size: "Medium",
    quantity: 1,
  },
  {
    id: 17,
    name: "Rain Jacket Women Windbreaker Striped Climbing Raincoats",
    price: 39.99,
    category: "women's clothing",
    image: "https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg",
    stock: 679,
    isSelected: false,
    color: "Yellow",
    size: "Small",
    quantity: 1,
  },
  {
    id: 18,
    name: "MBJ Women's Solid Short Sleeve Boat Neck V",
    price: 9.85,
    category: "women's clothing",
    image: "https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg",
    stock: 130,
    isSelected: false,
    color: "Pink",
    size: "Medium",
    quantity: 1,
  },
  {
    id: 19,
    name: "Opna Women's Short Sleeve Moisture",
    price: 7.95,
    category: "women's clothing",
    image: "https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg",
    stock: 146,
    isSelected: false,
    color: "Blue",
    size: "Large",
    quantity: 1,
  },
  {
    id: 20,
    name: "DANVOUY Womens T Shirt Casual Cotton Short",
    price: 12.99,
    category: "women's clothing",
    image: "https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg",
    stock: 145,
    isSelected: false,
    color: "White",
    size: "Small",
    quantity: 1,
  },
];

// export const products = [
//   {
//     name: "Hoodie",
//     color: "Red",
//     stock: 10,
//     price: 100,
//     category: "Clothes",
//     size: "M",
//     id: 1,
//     quantity: 1,
//     isSelected: false,
//   },
//   {
//     name: "Tshirt",
//     color: "Red",
//     stock: 0,
//     price: 100,
//     category: "Clothes",
//     size: "M",
//     id: 6,
//     quantity: 1,
//     isSelected: false,
//   },
//   {
//     name: "Jeans",
//     color: "Blue",
//     stock: 5,
//     price: 200,
//     category: "Shoes",
//     size: "L",
//     id: 2,
//     quantity: 1,
//     isSelected: false,
//   },
//   {
//     name: "Shirt",
//     color: "Green",
//     stock: 15,
//     price: 150,
//     category: "Clothes",
//     size: "S",
//     id: 3,
//     quantity: 1,
//     isSelected: false,
//   },
// ];
